/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRoutesRouteImport } from './routes/_ProtectedRoutes'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as ProtectedRoutesHomeRouteImport } from './routes/_ProtectedRoutes/home'

const ProtectedRoutesRoute = ProtectedRoutesRouteImport.update({
  id: '/_ProtectedRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoutesHomeRoute = ProtectedRoutesHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoutesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/Login': typeof LoginRoute
  '/': typeof ProtectedRoutesRouteWithChildren
  '/home': typeof ProtectedRoutesHomeRoute
}
export interface FileRoutesByTo {
  '/Login': typeof LoginRoute
  '/': typeof ProtectedRoutesRouteWithChildren
  '/home': typeof ProtectedRoutesHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/Login': typeof LoginRoute
  '/_ProtectedRoutes': typeof ProtectedRoutesRouteWithChildren
  '/_ProtectedRoutes/home': typeof ProtectedRoutesHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Login' | '/' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/Login' | '/' | '/home'
  id: '__root__' | '/Login' | '/_ProtectedRoutes' | '/_ProtectedRoutes/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  ProtectedRoutesRoute: typeof ProtectedRoutesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ProtectedRoutes': {
      id: '/_ProtectedRoutes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedRoutes/home': {
      id: '/_ProtectedRoutes/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedRoutesHomeRouteImport
      parentRoute: typeof ProtectedRoutesRoute
    }
  }
}

interface ProtectedRoutesRouteChildren {
  ProtectedRoutesHomeRoute: typeof ProtectedRoutesHomeRoute
}

const ProtectedRoutesRouteChildren: ProtectedRoutesRouteChildren = {
  ProtectedRoutesHomeRoute: ProtectedRoutesHomeRoute,
}

const ProtectedRoutesRouteWithChildren = ProtectedRoutesRoute._addFileChildren(
  ProtectedRoutesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  ProtectedRoutesRoute: ProtectedRoutesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
